version: 0.1
phases:
  install:
    commands:
      - npm install
      # - npm install -g mocha
      # - npm install -g serverless
  build:
    commands:
      - npm run deploy
  post_build:
    commands:
      - npm test